use_frameworks!

platform :ios, '9.0'

target 'PDNetworking_Example' do
  pod 'PDNetworking', :path => '../'
  pod 'AFNetworking'
  pod 'YYCache'

  target 'PDNetworking_Tests' do
    inherit! :search_paths

    
  end
end
